name: Build
on: [push]

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel nuitka zstandard
        pip install -r requirements.txt
        curl https://files.jrsoftware.org/is/6/innosetup-6.2.0.exe -o is.exe
        ./is.exe /VERYSILENT /NORESTART /SUPPRESSMSGBOXES /ALLUSERS /NOCANCEL
    - name: Build application
      run: python -m nuitka playcord --follow-imports --assume-yes-for-downloads --output-dir=dist --no-pyi-file --include-package=playcord --standalone --prefer-source-code --remove-output --windows-company-name="Yusuf Cihan" --windows-icon-from-ico="misc/playcord_logo.ico" --windows-product-name="Playcord" --windows-product-version="1.0" --windows-uac-admin --windows-file-description=Playcord
    - name: Build installer
      run: '"%programfiles(x86)%\Inno Setup 6\iscc.exe" "misc/installer_script.iss"'
      shell: cmd
    - name: Upload installer to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: playcord-installer
        path: Playcord.exe