name: Build
on: [push]

jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install https://github.com/ysfchn/briefcase/archive/feature/custom-uri.zip
    - name: Build application
      run: briefcase package
    - name: Upload installer to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: playcord-windows
        path: windows/*.msi
  
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install libgirepository1.0-dev libcairo2-dev libpango1.0-dev unzip
        pip install wheel
        pip install https://github.com/ysfchn/briefcase/archive/feature/custom-uri.zip
    - name: Build application
      run: briefcase package
    - name: Upload installer to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: playcord-linux
        path: linux/*.AppImage